#!/bin/bash

curl -o /var/www/html/waposatdev/wptest/servScr/temp "http://monitoreo.waposat.com/monitor/abc|123|10|1.74|6|79.08|3|56.61|1|84.12|14|56.32|13|29.97"
curl -o /var/www/html/waposatdev/wptest/servScr/temp "http://monitoreo.waposat.com/monitor/def|123|11|31.72|2|82.82|6|89.49|9|74.91|10|84.77"
