# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.dataloader:
          class: AppBundle\Service\DataLoader
          arguments:
            entityManager: "@doctrine.orm.entity_manager"

      app.mailer:
          class: AppBundle\Service\Mailer
          arguments:
            entityManager: "@doctrine.orm.entity_manager"

