<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SensorModels extends \AppBundle\Entity\SensorModels implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'maxLimit', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'minLimit', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'idSensorModel', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'idMeasurementUnit', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'idParameter'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'maxLimit', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'minLimit', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'idSensorModel', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'idMeasurementUnit', '' . "\0" . 'AppBundle\\Entity\\SensorModels' . "\0" . 'idParameter'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SensorModels $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setMaxLimit($maxLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxLimit', [$maxLimit]);

        return parent::setMaxLimit($maxLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxLimit', []);

        return parent::getMaxLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinLimit($minLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinLimit', [$minLimit]);

        return parent::setMinLimit($minLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinLimit', []);

        return parent::getMinLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSensorModel()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdSensorModel();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSensorModel', []);

        return parent::getIdSensorModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMeasurementUnit(\AppBundle\Entity\MeasurementsUnits $idMeasurementUnit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMeasurementUnit', [$idMeasurementUnit]);

        return parent::setIdMeasurementUnit($idMeasurementUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMeasurementUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMeasurementUnit', []);

        return parent::getIdMeasurementUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdParameter(\AppBundle\Entity\Parameters $idParameter = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdParameter', [$idParameter]);

        return parent::setIdParameter($idParameter);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdParameter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdParameter', []);

        return parent::getIdParameter();
    }

}
