<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MonitoringEvents extends \AppBundle\Entity\MonitoringEvents implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MonitoringEvents' . "\0" . 'idMonitoringEvent', '' . "\0" . 'AppBundle\\Entity\\MonitoringEvents' . "\0" . 'idMeasurement', '' . "\0" . 'AppBundle\\Entity\\MonitoringEvents' . "\0" . 'idBlockSensor', '' . "\0" . 'AppBundle\\Entity\\MonitoringEvents' . "\0" . 'idEventType'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MonitoringEvents' . "\0" . 'idMonitoringEvent', '' . "\0" . 'AppBundle\\Entity\\MonitoringEvents' . "\0" . 'idMeasurement', '' . "\0" . 'AppBundle\\Entity\\MonitoringEvents' . "\0" . 'idBlockSensor', '' . "\0" . 'AppBundle\\Entity\\MonitoringEvents' . "\0" . 'idEventType'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MonitoringEvents $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdMonitoringEvent()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdMonitoringEvent();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMonitoringEvent', []);

        return parent::getIdMonitoringEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMeasurement(\AppBundle\Entity\Measurement $idMeasurement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMeasurement', [$idMeasurement]);

        return parent::setIdMeasurement($idMeasurement);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMeasurement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMeasurement', []);

        return parent::getIdMeasurement();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdBlockSensor(\AppBundle\Entity\BlockSensors $idBlockSensor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdBlockSensor', [$idBlockSensor]);

        return parent::setIdBlockSensor($idBlockSensor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdBlockSensor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBlockSensor', []);

        return parent::getIdBlockSensor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEventType(\AppBundle\Entity\EventType $idEventType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEventType', [$idEventType]);

        return parent::setIdEventType($idEventType);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEventType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEventType', []);

        return parent::getIdEventType();
    }

}
